version: '3.3'
services:
  app:
    container_name: notifyer-ci
    build: ./
    environment:
      NOTIFYER_TELEGRAM_BOT_TOKEN: ""
      CI_PROJECT_URL: ""
      CI_PIPELINE_ID: ""
      CI_COMMIT_REF_SLUG: ""
      NOTIFYER_TELEGRAM_CHAT_ID:
      NOTIFYER_TEXT: "Release ready!"
      NOTIFYER_TELEGRAM_PARSE_MODE: "HTML"
    command: notifyer --text "<pre>Release done</pre><pre>pre-formatted</pre>" --telegram_parse_mode "HTML" deploy done